---
galaxy_info:
  author: zedr
  description: Provision a Gitlab Runner instance using Podman
  role_name: gitlab_runner
  namespace: zedr
  license: BSD-3-Clause
  min_ansible_version: 2.10
  platforms:
    - name: Fedora
      versions:
        - 33

  galaxy_tags:
    - gitlab
